defaults:
  - data: cal_housing
  - model: random_forest
  - grid_search: null

run_name: "run_default"
task: regression   # or "classification"

mlflow:
  experiment_name: "hydra_mlflow_experiment"

data:
  name: cal_housing

model:
  name: random_forest
  params:
    n_estimators: 100
    random_state: 42

grid_search:
  enabled: false
  param_grid: {}
  cv: 5
  scoring: r2
  n_jobs: -1
  verbose: 1
